version: "3.9"
services:
  postgres14-devsu:
    container_name: postgres14-devsu
    image: postgres:14-alpine
    ports:
      - "5440:5432"
    environment:
      POSTGRES_PASSWORD: sasa
      POSTGRES_DB: devsudb
    volumes:
      - data-postgres14:/var/lib/postgresql/data
    restart: always
    networks:
      - red-devsu

  devsu-cliente:
    container_name: devsu-cliente
    build:
      context: ./
      dockerfile: ./devsu-cliente/Dockerfile
    ports:
      - "8001:8001"
    env_file: ./devsu-cliente/.env
    networks:
      - red-devsu
    depends_on:
      - postgres14-devsu
    restart: always

  devsu-cuenta-mov:
    container_name: devsu-cuenta-mov
    build:
      context: ./
      dockerfile: ./devsu-cuenta-mov/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./devsu-cuenta-mov/.env
    networks:
      - red-devsu
    depends_on:
      - postgres14-devsu
      - devsu-cliente
    restart: always
volumes:
  data-postgres14:
    name: data-postgres14

networks:
  red-devsu:
    name: red-devsu